os: linux
language: java

services:
  - docker

before_install:
  - docker run -dp 27017:27017 --name mongotest mongo
  - chmod +x ./gradlew

script: ./gradlew check --console=plain

deploy:
  provider: script
  script: ./gradlew bintrayUpload --console=plain
  skip_cleanup: true
  on:
    tags: true
    branch: master
